services:
  java:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
        MY_USER: $MY_USER
        MY_GROUP: $MY_GROUP
        TZ: $TZ
    env_file:
      - .env
    working_dir: "/home/${MY_USER}/app"
    user: ${MY_USER}:${MY_GROUP}
    volumes:
      - type: bind
        source: ./
        target: "/home/${MY_USER}/app"
    tty: true
    entrypoint: sh
